const LOAD_USER = "LOAD_USER";
const ADD_LIQUIDITY = "ADD_LIQUIDITY";
const REMOVE_LIQUIDITY = "REMOVE_LIQUIDITY";
const RUN_SWAP = "RUN_SWAP";
const APPROVE_LIQUIDITY = "APPROVE_LIQUIDITY";
const APPROVE_REMOVE_LIQUIDITY = "APPROVE_REMOVE_LIQUIDITY";
const APPROVE_SWAP = "APPROVE_SWAP";
export { LOAD_USER, ADD_LIQUIDITY, REMOVE_LIQUIDITY, APPROVE_LIQUIDITY, APPROVE_REMOVE_LIQUIDITY, RUN_SWAP, APPROVE_SWAP };
